# Generated by Django 5.1.2 on 2024-11-11 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminsettings",
            name="restricted_end",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="adminsettings",
            name="restricted_start",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
